Repository gazebosim/gz-utils, pull requests merged in 2022-07, with the labels that each got.

#71 Merge ign-utils1 ➡️ main
  cli/include/vendored-cli/gz/utils/cli/FormatterFwd.hpp
  cli/src/cli_TEST.cc
Labels: 🌱 garden

#70 ign -> gz Provisional Finale: Source Migration : gz-utils
  Migration.md
  cli/include/gz/utils/cli/GzFormatter.hpp
  cli/src/cli_TEST.cc
Labels: 🌱 garden, ign to gz

#74 Implement ExtraTestMacros for all platforms
  include/gz/utils/ExtraTestMacros.hh
  include/gz/utils/detail/ExtraTestMacros.hh
Labels: 🌱 garden

#72 Add code coverage ignore file
  CMakeLists.txt
  coverage.ignore.in
Labels: bug, 🏯 fortress, QA
